/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c_AcessoBD;

import java.sql.Connection;

/**
 *
 * @author danie
 */
public class C01_InserirProduto extends javax.swing.JFrame {

    /**
     * Creates new form C01_InserirProduto
     */
    public C01_InserirProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputNome = new javax.swing.JTextField();
        inputPreco = new javax.swing.JTextField();
        inputFabricante = new javax.swing.JTextField();
        inputMaterial = new javax.swing.JTextField();
        inputTamanho = new javax.swing.JTextField();
        inputTipoUso = new javax.swing.JTextField();
        inputCor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAdicinar = new javax.swing.JButton();
        descricao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(420, 300));
        setMinimumSize(new java.awt.Dimension(420, 300));
        getContentPane().setLayout(null);

        inputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeActionPerformed(evt);
            }
        });
        getContentPane().add(inputNome);
        inputNome.setBounds(80, 30, 210, 20);
        getContentPane().add(inputPreco);
        inputPreco.setBounds(80, 50, 210, 20);
        getContentPane().add(inputFabricante);
        inputFabricante.setBounds(80, 70, 210, 20);
        getContentPane().add(inputMaterial);
        inputMaterial.setBounds(80, 90, 210, 20);
        getContentPane().add(inputTamanho);
        inputTamanho.setBounds(80, 110, 210, 20);
        getContentPane().add(inputTipoUso);
        inputTipoUso.setBounds(80, 130, 210, 20);

        inputCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCorActionPerformed(evt);
            }
        });
        getContentPane().add(inputCor);
        inputCor.setBounds(80, 150, 210, 20);

        jLabel1.setText("Cor:");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 150, 80, 20);

        btnAdicinar.setText("Adicionar Produto");
        btnAdicinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicinarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicinar);
        btnAdicinar.setBounds(10, 170, 280, 23);

        descricao.setText("Insere caracteristicas embaixo");
        getContentPane().add(descricao);
        descricao.setBounds(80, 10, 210, 20);

        jLabel3.setText("Nome:");
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 30, 80, 20);

        jLabel4.setText("Preço:");
        jLabel4.setToolTipText("");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 50, 80, 20);

        jLabel5.setText("Fabricante:");
        jLabel5.setToolTipText("");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 70, 80, 20);

        jLabel6.setText("Material:");
        jLabel6.setToolTipText("");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 90, 80, 20);

        jLabel7.setText("Tamanho:");
        jLabel7.setToolTipText("");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 110, 80, 20);

        jLabel8.setText("Tipo de Uso:");
        jLabel8.setToolTipText("");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 130, 80, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCorActionPerformed

    private void inputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeActionPerformed

    private void btnAdicinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicinarActionPerformed
        Connection ligacao = FuncoesBaseDeDados.ligacao();
        String nome = inputNome.getText();
        float preco = Float.parseFloat(inputPreco.getText());
        String fabricante = inputFabricante.getText();
        String material = inputMaterial.getText();
        int tamanho = Integer.parseInt(inputTamanho.getText());
        String uso = inputTipoUso.getText();
        String cor = inputCor.getText();
        FuncoesBaseDeDados.insereBola(ligacao, nome, preco, fabricante, material, tamanho, uso, cor);
        inputNome.setText("");
        inputPreco.setText("");
        inputFabricante.setText("");
        inputMaterial.setText("");
        inputTamanho.setText("");
        inputTipoUso.setText("");
        inputCor.setText("");
        descricao.setText("Operação Feita!!");
    }//GEN-LAST:event_btnAdicinarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C01_InserirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C01_InserirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C01_InserirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C01_InserirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C01_InserirProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicinar;
    private javax.swing.JLabel descricao;
    private javax.swing.JTextField inputCor;
    private javax.swing.JTextField inputFabricante;
    private javax.swing.JTextField inputMaterial;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputPreco;
    private javax.swing.JTextField inputTamanho;
    private javax.swing.JTextField inputTipoUso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
